/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

@org.apache.avro.specific.AvroGenerated
public class LetterCountOutputAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7957243351150969527L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LetterCountOutputAvro\",\"fields\":[{\"name\":\"Letter\",\"type\":\"string\"},{\"name\":\"Count\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LetterCountOutputAvro> ENCODER =
      new BinaryMessageEncoder<LetterCountOutputAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LetterCountOutputAvro> DECODER =
      new BinaryMessageDecoder<LetterCountOutputAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<LetterCountOutputAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<LetterCountOutputAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<LetterCountOutputAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<LetterCountOutputAvro>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this LetterCountOutputAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a LetterCountOutputAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a LetterCountOutputAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static LetterCountOutputAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence Letter;
  private int Count;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LetterCountOutputAvro() {}

  /**
   * All-args constructor.
   * @param Letter The new value for Letter
   * @param Count The new value for Count
   */
  public LetterCountOutputAvro(java.lang.CharSequence Letter, java.lang.Integer Count) {
    this.Letter = Letter;
    this.Count = Count;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Letter;
    case 1: return Count;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Letter = (java.lang.CharSequence)value$; break;
    case 1: Count = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'Letter' field.
   * @return The value of the 'Letter' field.
   */
  public java.lang.CharSequence getLetter() {
    return Letter;
  }


  /**
   * Sets the value of the 'Letter' field.
   * @param value the value to set.
   */
  public void setLetter(java.lang.CharSequence value) {
    this.Letter = value;
  }

  /**
   * Gets the value of the 'Count' field.
   * @return The value of the 'Count' field.
   */
  public int getCount() {
    return Count;
  }


  /**
   * Sets the value of the 'Count' field.
   * @param value the value to set.
   */
  public void setCount(int value) {
    this.Count = value;
  }

  /**
   * Creates a new LetterCountOutputAvro RecordBuilder.
   * @return A new LetterCountOutputAvro RecordBuilder
   */
  public static LetterCountOutputAvro.Builder newBuilder() {
    return new LetterCountOutputAvro.Builder();
  }

  /**
   * Creates a new LetterCountOutputAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LetterCountOutputAvro RecordBuilder
   */
  public static LetterCountOutputAvro.Builder newBuilder(LetterCountOutputAvro.Builder other) {
    if (other == null) {
      return new LetterCountOutputAvro.Builder();
    } else {
      return new LetterCountOutputAvro.Builder(other);
    }
  }

  /**
   * Creates a new LetterCountOutputAvro RecordBuilder by copying an existing LetterCountOutputAvro instance.
   * @param other The existing instance to copy.
   * @return A new LetterCountOutputAvro RecordBuilder
   */
  public static LetterCountOutputAvro.Builder newBuilder(LetterCountOutputAvro other) {
    if (other == null) {
      return new LetterCountOutputAvro.Builder();
    } else {
      return new LetterCountOutputAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for LetterCountOutputAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LetterCountOutputAvro>
    implements org.apache.avro.data.RecordBuilder<LetterCountOutputAvro> {

    private java.lang.CharSequence Letter;
    private int Count;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(LetterCountOutputAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Letter)) {
        this.Letter = data().deepCopy(fields()[0].schema(), other.Letter);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.Count)) {
        this.Count = data().deepCopy(fields()[1].schema(), other.Count);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing LetterCountOutputAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(LetterCountOutputAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.Letter)) {
        this.Letter = data().deepCopy(fields()[0].schema(), other.Letter);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Count)) {
        this.Count = data().deepCopy(fields()[1].schema(), other.Count);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'Letter' field.
      * @return The value.
      */
    public java.lang.CharSequence getLetter() {
      return Letter;
    }


    /**
      * Sets the value of the 'Letter' field.
      * @param value The value of 'Letter'.
      * @return This builder.
      */
    public LetterCountOutputAvro.Builder setLetter(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.Letter = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Letter' field has been set.
      * @return True if the 'Letter' field has been set, false otherwise.
      */
    public boolean hasLetter() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'Letter' field.
      * @return This builder.
      */
    public LetterCountOutputAvro.Builder clearLetter() {
      Letter = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Count' field.
      * @return The value.
      */
    public int getCount() {
      return Count;
    }


    /**
      * Sets the value of the 'Count' field.
      * @param value The value of 'Count'.
      * @return This builder.
      */
    public LetterCountOutputAvro.Builder setCount(int value) {
      validate(fields()[1], value);
      this.Count = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Count' field has been set.
      * @return True if the 'Count' field has been set, false otherwise.
      */
    public boolean hasCount() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Count' field.
      * @return This builder.
      */
    public LetterCountOutputAvro.Builder clearCount() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LetterCountOutputAvro build() {
      try {
        LetterCountOutputAvro record = new LetterCountOutputAvro();
        record.Letter = fieldSetFlags()[0] ? this.Letter : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.Count = fieldSetFlags()[1] ? this.Count : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LetterCountOutputAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<LetterCountOutputAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LetterCountOutputAvro>
    READER$ = (org.apache.avro.io.DatumReader<LetterCountOutputAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.Letter);

    out.writeInt(this.Count);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.Letter = in.readString(this.Letter instanceof Utf8 ? (Utf8)this.Letter : null);

      this.Count = in.readInt();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.Letter = in.readString(this.Letter instanceof Utf8 ? (Utf8)this.Letter : null);
          break;

        case 1:
          this.Count = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










